USE GesconDatabase;
GO
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('330802154', 'Mateo Bravo', 'carol87@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('799079461', 'Leonardo Herrera-Villarroel', 'luis27@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('68454635K', 'Evelyn Josefina Aburto Venegas', 'abarcacarlos@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('858826837', 'Erika Romero', 'valentinabravo@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('184644053', 'José Ian Vera Arce', 'fernandomunoz@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('647373089', 'Javiera Mariela Pérez Cerda', 'elcirameza@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('603754557', 'Alejandra Blanca Cancino Rubio', 'davidvilches@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('941453805', 'Aurelio Barrera', 'candiacarlos@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('573282787', 'Raúl Benjamín Sepúlveda Muñoz', 'earancibia@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('70925664', 'Eduardo Jaime Cerda Godoy', 'miguelperez@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('189745397', 'Ana Duarte Alvarado', 'mariacisternas@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('82665080K', 'Yessica Maureira-Fuentealba', 'cramos@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('837319331', 'Daniel Leonardo Ávila Soto', 'yenny78@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('510349067', 'Ignacio Barrientos Jiménez', 'carlosriquelme@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('999937802', 'Vicente Contreras', 'reyesvioleta@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('770456665', 'José Alejandro Rubio Brito', 'contrerasjoseph@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('880692771', 'María Carolina Salazar Astorga', 'florencia23@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('226407944', 'Natalia Henríquez', 'anamorales@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('197312424', 'Carlos Aliaga Mancilla', 'vasquezmyriam@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('885222757', 'Guillermo Patricio Barraza Villalobos', 'cescobar@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('657618160', 'Vanessa Torres', 'osorioolga@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('966022035', 'Rosa Bernardita Acevedo Benítez', 'raulquinteros@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('961804655', 'María Salazar Castillo', 'haydee34@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('58415936', 'Carolina Navarro', 'mirandapaola@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('47186862', 'Lilian Vilma Pavez Apablaza', 'maria41@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('95702880', 'Nidia Álvarez', 'espinozagaston@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('277014513', 'Diego Acevedo Riquelme', 'carolinaruz@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('460781736', 'Marta Rebolledo Villalobos', 'dgomez@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('99496215', 'Irma Castro', 'ibugueno@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('967748005', 'Gabriela Judith Rojas Avendaño', 'luis63@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('852696818', 'Pascale Nora Yáñez Vásquez', 'umorales@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('266328168', 'Lucas Bugueño Collao', 'cesar30@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('168002645', 'Carola Rita Hormazábal González', 'francis69@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('54870264K', 'Dominga Torres Silva', 'erodriguez@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('257493849', 'Cristian Espinoza Garrido', 'wleiva@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('980833089', 'Nicole Andrea Lagos Guajardo', 'daniela57@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('983534848', 'Sonia Andrea Urzúa Águila', 'carvajalrenato@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('55148198', 'Marianela Lucila Neira Barrientos', 'mespinoza@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('820640187', 'José Diego Pincheira Cárdenas', 'pachecomarcos@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('716072614', 'Franco Espinoza Morales', 'valenzuelarigoberto@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('177977179', 'María Segovia-López', 'norma71@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('543768421', 'Gabriel Carmona Velásquez', 'hernandezalexander@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('283388468', 'Jesús Pérez Campos', 'gumercindovidal@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('229126083', 'Rodrigo Flores', 'jgonzalez@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('812154672', 'Cristian Pedro Fernández Cancino', 'imolina@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('41721660K', 'Ema Henríquez Altamirano', 'joseabarca@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('621267868', 'Jeannette María Pizarro Araya', 'alonso07@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('373128538', 'María Velásquez', 'torresviviana@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('96422630K', 'Corina María Jara Espinosa', 'ingrid53@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('935158257', 'Rosa Javiera Álvarez Morales', 'jose01@example.net');
