USE GesconDatabase;
GO
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('609125195', 'José Juan Cárdenas Aguilera', 'trubilar@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('31159407', 'Viviana Carvajal', 'fmendez@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('410807343', 'Mercedes Neira Escalona', 'isabelrebolledo@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('642781499', 'Elizabeth Hilda Pineda Martínez', 'smaldonado@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('915647596', 'Raúl Héctor Paredes Ibarra', 'sofia21@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('871511217', 'Olga González Flores', 'juliocontreras@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('67580079', 'Edison Vallejos', 'conchajaime@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('107587659', 'María Riquelme Guzmán', 'jonathan34@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('930328979', 'Alex Ruz Valenzuela', 'ymunoz@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('933016870', 'Monserrat Lilian Pérez Villarroel', 'patriciasoto@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('514314934', 'Pía Isidora Allendes Castro', 'lmeneses@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('473998734', 'Ignacio Vergara Arcos', 'saragatica@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('59463876K', 'Carla Albornoz Rojas', 'hyanez@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('680412138', 'Freddy Germán Leiva Dinamarca', 'marcelocollao@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('424437786', 'Alex Damián Sepúlveda Barraza', 'dgajardo@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('45514358', 'Pilar Loreto Bustos Barrientos', 'tapiaveronica@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('385817533', 'Dominga Delia Trujillo Gómez', 'jose94@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('74617476', 'Makarena Ámbar Méndez Chávez', 'carol92@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('23577941', 'Margarita Contreras', 'nelidacardenas@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('58790745', 'Pablo José Muñoz Fuentealba', 'silvia88@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('149242708', 'Carlos Rojas Molina', 'sofiareyes@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('949788946', 'Nancy Leal', 'romeromarco@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('301319827', 'Isabel Navarro', 'gjimenez@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('903550295', 'Cristian Jorge Avilés Tobar', 'agustina56@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('100113317', 'Emilio Raúl Orellana Reyes', 'gfarias@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('280878626', 'Florencia Cecilia Rojas Norambuena', 'ofernandez@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('634473866', 'Patricia Muñoz Romero', 'angeloramirez@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('670735915', 'Camila Ana Guerrero Cerda', 'clopez@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('45789371K', 'María Antonia Matus Ojeda', 'castroana@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('193231497', 'Daniel Gómez Tapia', 'sergio82@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('300450695', 'Manuel Simón Cabezas García', 'xpalma@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('836152530', 'Jael Hidalgo Zúñiga', 'crubio@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('551518000', 'Noelia Paulina Sanhueza Garay', 'reyesraquel@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('400257779', 'María Aguilar', 'ysilva@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('272782571', 'José Valenzuela Alvarez', 'bastian94@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('42660535K', 'Jesús Moreno', 'palmaveronica@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('388281146', 'Cecilia Isabella López Pinto', 'pzuniga@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('432618366', 'Rigoberto Guillermo Vásquez Muñoz', 'mriquelme@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('785593219', 'Marcos Aravena', 'mia03@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('166438691', 'Paola Astorga Espinoza', 'nvega@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('944014047', 'Margarita Martínez Fuentes', 'zsalamanca@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('946205729', 'Javiera Caballero', 'qibanez@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('350935169', 'Florencia Cortés', 'jose12@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('565826743', 'Francisca Claudia Parra Moya', 'tomas88@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('385379617', 'Ingrid Román Machuca', 'narredondo@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('189048580', 'Andrea Romina Mancilla Cárcamo', 'avilamaria@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('226414703', 'Nancy Josefa Gutiérrez Araya', 'leonulises@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('482779247', 'Elisa Alejandra Álvarez Yáñez', 'bsolar@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('371707735', 'Monserrat Macarena Gallardo Morales', 'pardomaite@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('198762032', 'Ricardo Ponce', 'pobletejean@example.net');
