USE GesconDatabase;
GO
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('849675974', 'Mauricio Rodrigo González Contreras', 'angela72@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('190475557', 'Karen Martínez Gatica', 'alegriamatias@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('403375608', 'Rosa Claudia Espinoza Cárdenas', 'carlos43@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('959767114', 'Carlos Iván Pacheco Torres', 'ogalleguillos@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('880903837', 'Daniel Miguel Vera Vidal', 'eruiz@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('920282881', 'Giselle Paula Rojas Hernández', 'espinozajose@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('361387600', 'Karla Carmen González Angulo', 'jgarcia@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('611236964', 'Zoila Aguirre', 'vflores@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('718611822', 'Juan Montecino Fierro', 'sbaeza@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('676682686', 'Pedro Poblete', 'mariamolina@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('123192524', 'Mariluz Vidal', 'tapiaana@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('72791142', 'Wilfredo Octavio Aguilera Rebolledo', 'hermanvelasquez@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('139076729', 'Héctor Enrique González González', 'baltazar37@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('77568335K', 'Constanza Aguilera Mansilla', 'diazpatricio@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('202304265', 'Jeremy Juan Paredes Pérez', 'mario70@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('189091893', 'Jaime Eduardo Barría-Iturra Osorio', 'acunafrancisca@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('181862440', 'María Maureira Riquelme', 'bernarditasandoval@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('704817657', 'Mauricio Roberto Osorio Barra', 'caceresabraham@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('513181094', 'Máximo Pedro Herrera Ríos', 'ossessergio@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('610216099', 'Manuel Vicente Pérez Vargas', 'isidorafuentes@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('14683569', 'Marta Herrera San Martín', 'utroncoso@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('12493894', 'Oscar Víctor Bórquez Aburto', 'joaquin10@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('989600281', 'Guillermo Vicente Vega Sepúlveda', 'dolores74@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('483007116', 'Isabel Raquel Prado Sánchez', 'luis66@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('360854485', 'Aurora Macarena Contreras Núñez', 'ana20@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('389665398', 'Nicole Isidora Carvajal Alarcón', 'gonzalezanita@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('654303800', 'Germán Leyton', 'cortezclemente@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('331383643', 'Catalina Inzunza Pérez', 'cornejonatalia@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('403749206', 'Danae Quezada Bustamante', 'kacevedo@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('22263802K', 'Fernando José Troncoso Quiroga', 'marcelocortez@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('508384122', 'Cristian Héctor Ruiz Poblete', 'pachecojimena@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('5825946', 'Anaís Alegría Muñoz', 'lpena@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('833487035', 'Antonia Constanza Valencia Hernández', 'lsanchez@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('514217599', 'Cristian Ampuero Paredes', 'xmeza@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('102479602', 'Víctor Ignacio Rodríguez Cortés', 'molinapatricia@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('382428285', 'Raúl Jhonny Rodríguez Ramos', 'tgarrido@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('359723822', 'Lorenzo Diego Canales Vilches', 'delgadokarin@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('54109520', 'Valentina Agurto Pacheco', 'sofia69@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('662888990', 'Yanet Baez Araneda', 'osvaldo97@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('275983705', 'Salvador Espinoza González', 'yanetpoblete@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('270337252', 'Florencia Rocío Galleguillos Bravo', 'jose64@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('415978413', 'Carlos Angelo Inzunza Paredes', 'roman17@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('906770334', 'María Millaray Martínez Salas', 'hcampos@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('199662155', 'Emily Katherine Cuevas Bravo', 'catalanmarcia@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('84891665K', 'Javiera Daniela Donoso Vásquez', 'maria54@example.com');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('942247648', 'Paula Alejandra Acevedo Sandoval', 'wretamal@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('659123142', 'Herminda Rosa García Cortés', 'gonzalo67@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('300110401', 'Claudia Román', 'yolandaalarcon@example.org');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('894140879', 'Santiago Garcés Escobar', 'paola18@example.net');
INSERT INTO Revisores (rut_revisor, nombre_revisor, correo_revisor) VALUES ('709564846', 'Mariana Rocío Lagos Plaza', 'matiasalbornoz@example.org');
