USE GesconDatabase;
GO
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('89112063K', 'Nicole Gómez', 'carolina13@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('97024073K', 'David Sánchez', 'lobossolange@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('605012833', 'Norma Sofía Torres Mardones', 'mateofuentes@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('128650806', 'Freddy Patricio Cárdenas Chávez', 'ignaciahenriquez@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('424254657', 'Fernanda Molina', 'astudillobenjamin@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('367930217', 'Ezequiel Vargas Ortiz', 'irenepalma@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('907987434', 'Rosa Paola Poblete Erices', 'maricelapino@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('55527679', 'Fabiola Sánchez Arellano', 'lalvarez@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('251910464', 'Marcela Guadalupe Hernández Gallardo', 'zcontreras@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('318510504', 'Ivonne Fiorella Baeza García', 'jocelyn44@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('385296797', 'Héctor Carvajal Avendaño', 'natalia39@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('843379621', 'Emilia Antonia Rodríguez Retamales', 'toledobarbara@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('447578611', 'Mónica Muñoz Beltrán', 'alarconricardo@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('866625018', 'Juan Felipe Tobar Angulo', 'hidalgoamaya@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('808735865', 'Jennifer Garrido Rivas', 'ignacio97@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('995768909', 'Digna Martina Muñoz Castillo', 'jonathan64@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('313084701', 'Hernán Yáñez Bustamante', 'magdalenarocha@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('927664054', 'Camila Adriana De La Fuente García', 'fernanda26@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('757490609', 'Martín Lorenzo Torres Montenegro', 'segueldaniel@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('618818306', 'Francisco Araneda Díaz', 'fernando89@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('549670423', 'Luisa Noemí Valderrama Vásquez', 'ysoto@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('481118921', 'Alejandro González Gallegos', 'blancamoreno@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('84229539', 'Mario Muñoz', 'guerradennis@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('578806121', 'Augusto Edgardo Álvarez Quezada', 'josevaldes@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('381655709', 'Ángel José Romero Pérez', 'njara@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('777649086', 'Ingrid Rosa Cabezas Catalán', 'luis68@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('61617612', 'David Erick Ruiz Rojas', 'munozsebastian@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('406592227', 'Marlene Elsa Gamboa Flores', 'patricioramirez@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('238136512', 'Joaquín Manuel López Castro', 'marisolmorales@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('986952748', 'Thiare Inés Toro Vega', 'eduardobrito@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('59786075', 'María Gloria Poblete Acevedo', 'ydiaz@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('467222600', 'Olivia Amelia Pulgar Soto', 'agonzalez@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('995877090', 'Félix José Torres Mondaca', 'rcerda@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('470697504', 'Violeta Espinoza', 'clementinamatus@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('148900132', 'Clemente Correa Garrido', 'luisacastillo@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('990691363', 'Hipólito Cárdenas Vera', 'lealana@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('336977762', 'Camila Ángela Acevedo Bustamante', 'contrerasmonica@example.net');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('61403419K', 'Benjamín Juan Jara Cancino', 'renatomontero@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('59463039', 'Mónica Alondra González Muñoz', 'correahernan@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('365342156', 'María Santibáñez López', 'olgamoreno@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('338494726', 'Carmen García Olguín', 'jacqueline56@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('857158210', 'Ana Mariana Quispe Valenzuela', 'lazcanovicente@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('528582141', 'Anahí Droguett Galaz', 'alex95@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('127514402', 'Víctor Julián Silva Ramírez', 'ngonzalez@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('571600501', 'Valentina Urrutia Aguilar', 'zavalapascual@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('47058369K', 'Jesús Esteban Catalán Rodríguez', 'opavez@example.com');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('750691005', 'Florencia Farías Garrido', 'lbaeza@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('658674617', 'Ignacio Daniel Silva Rojas', 'rodrigo22@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('755542326', 'José Alejandro Cáceres Bustos', 'anahiconcha@example.org');
INSERT INTO Autores (rut_autor, nombre_autor, correo_autor) VALUES ('900031475', 'Juan Rojas', 'santos89@example.net');
